function b = add_button(parent, name, w)
children = get(parent, 'Children');
hpad = .025;

if (isempty(children))
    pos = [hpad hpad w 0.90];
else
    pos = get(children(1), 'Position');
    if (w < 0)
        w = (1 - (pos(1) + pos(3) + hpad) - hpad);
    end
    pos(1) = pos(1) + pos(3) + hpad;
    pos(3) = w;
end

b = uicontrol(...
    'Parent',parent,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','normalized',...
    'String',name,...
    'Style','pushbutton',...
    'Position',pos,...
    'Children',[],...
    'KeyPressFcn',blanks(0),...
    'ParentMode','manual',...
    'CreateFcn',blanks(0),...
    'DeleteFcn',blanks(0),...
    'ButtonDownFcn',blanks(0),...
    'FontSize',GetReleaseFontSize(),...
    'Tag',sprintf('uicontrol_%s', matlab.lang.makeValidName(name)));

% Get the calling function to make the callback name.
[stack,~] = dbstack;
stack = stack(2);
set(b, 'Callback', eval(sprintf('@(hObject,eventdata)%s(''%s_callback'',hObject,eventdata,guidata(hObject))', ...
    strrep(stack.file, '.m', ''), matlab.lang.makeValidName(name))));
