function h = make_panel(parent, name, pos, units, varargin)
h = uipanel('Parent',parent,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'BackgroundColor',[1 1 1],...
    'BorderWidth',1.5,...
    'Units',units,...
    'ShadowColor',get(0,'defaultuipanelShadowColor'),...
    'Title',name,...
    'Position', pos,...
    'ParentMode','manual',...
    'Tag', sprintf('uipanel_%s', matlab.lang.makeValidName(name)),...
    'FontSize', 12,...
    'FontWeight','bold',...
    'Visible','off', varargin{:});
